### ISSUE TITLE
Does not work for dependencies following the WordPress file naming pattern

### ISSUE THREAD

**Issue by mundschenk-at** [coenjacobs/mozart#18]
Libraries following the WordPress naming pattern (`class-some-name.php`) need to use the classmap autoloader. `mozart` treats these as old, pseudo-namespaces classes even when they are namespaced.

**Comment by coenjacobs** [comment]
Yeah, that's something I honestly don't know how to fix - or even think this is up to Mozart to support at this point. The WordPress class/file naming pattern is odd, to say the least. This is exactly what PSR-0 and PSR-4 have been designed for, to be a standard for autoloading.

I'm open to suggestions on how this could be supported by Mozart, but if I were you, I'd leave the WordPress naming pattern for what it is and start using proven autoloading standards.

**Comment by mundschenk-at** [comment]
Could you maybe either detect the presence of a namespace by parsing, or add an annotation field in the "extra" section? Something like "classmap-namespaced-packages"?

I could of course switch my own libraries over (though I prefer the WordPress layout, as I'm not a fan of camel-case), but what about other dependencies that exist in the wild? Technically, doing an autoloader for the WordPress-style filenames is no more difficult than for PSR-4 ones (other than that Composer only offers classmaps). If there's a way to make this work, I think this would be beneficial to the WordPress community.

**Comment by coenjacobs** [comment]
The thing with WordPress class naming conventions, is that it doesn't imply what kind of files it contains. I kinda like the idea of including support for it, but not decided on what way I'm going with it. I'm open to suggestions via pull requests, but I need to think it through for a little while.

**Comment by mundschenk-at** [comment]
What do you mean by "doesn't imply what kind of files it contains"?

**Comment by coenjacobs** [comment]
PSR-0 and PSR-4 autoloading standards imply that the classes contained in that autoloader are _namespaced_. Classmap autoloading _can_ contain namespaced classes, but doesn't have to. Therefore you can't determine if they contain namespaces or not, just by looking at the autoloader of the package and thus that makes the PSR-0 and PSR-4 autoloading standards superiour and prefered (pretty much everywhere outside of the WordPress world).

**Comment by mundschenk-at** [comment]
OK, yes, I assumed that this was the problem. I'll have a look if I can add an annotation to have them treated as namespaced. Of course that will only work for direct dependencies, not anything that comes up in the recursive tree.

**Comment by coenjacobs** [comment]
I have pulled the trigger on this case, after thinking this through for a long, _looong_ time. This is not something that I wish to support in the current state of Mozart. It is unreliable at best, so I'd rather choose to not support it at all at this point. The reason why both PSR-0 and PSR-4 work so great is because it is implied what kind of files are in the directories spanned by the namespace. The WordPress naming pattern is essentially a mix of standards, resulting in an unreliable way of determining what kind of files are being applied with the autoloader and thus not really a standard.

Perhaps my opinion might change in the future, or someone else can propose a great way to implement this. Feel free to propose a solution via a PR.
