### ISSUE TITLE
Mozart Compose fails for Twig

### ISSUE THREAD

**Issue by BenceSzalai** [coenjacobs/mozart#30]
May affect other packages as well, but I've encountered it when trying to use `twig/twig`.

Mozart gives an error: `File already exists at path: dependencies/Twig/Compiler.php`

The issue is caused by both psr-0 and psr-4 is being defined in the autoload section of Twig's composer.json in a way, that Mozart attempts to copy the files from both the psr-0 folder (lib/) and the psr-4 folder (src/) to the dep_directory, but as the two folders in Twig has the same files it fails.
```
...
"autoload": {
        "psr-0" : {
            "Twig_" : "lib/"
        },
        "psr-4" : {
            "Twig\\" : "src/"
        }
    },
...
```

A dirty workaround/test was that i've removed the psr-0 autoload definition from Twig's composer.json, and it worked, however obviously this is not a good solution in the long term.

Would it be possible to introduce a way to tell Mozart to only use one given autoload method defined in a package or any other way to handle this case in a way that does not involve messing with the composer.json of the dependencies? Or alternatively any other way to prevent it from trying to merge the two different folders and causing conflict?

**Comment by coenjacobs** [comment]
Thanks for reporting. I think this is one of the flaws in Mozart currently, where it doesn't properly know how to deal with multiple namespace based autoloaders in the same package (and results in `File already exists` errors. This is because Mozart rewrites the path of the package to become `%dep_namespace%/%package_slug%` and therefore tries to write both PSR-0 and PSR-4 to the same directory. This leads to a bit of a mess in this case and other packages with similar autoloader setups. I've seen this happen more often, but don't have an approach to solve this yet ready.

I'm open to ideas on how to a) solve this via configuration by excluding certain autoloaders or weird configurations in packages autoloaders, or b) have a way to deal with it when multiple namespace autoloaders are present in the same package.

**Comment by Grapestain** [comment]
In order to find the best solution I'd take a look at east a few different affected packages to see what they have in common and what not. Do you have a list of few others maybe?

For solution, unless a more complex pattern can be identified from multiple examples, I'd say possible strategies could be (in rough ascending order of difficulty to implement (as far as i can guess) and versatility of usage:
a.) add an option (boolean) to ignore psr-0 all together (but should be configurable, even though psr-0 is old, some may still use it)
b.) add an option (array of strings) to ignore psr-0 for a given list of packages
c.) add an option (2x boolean or 1 string with 3 possible values: `none`,`psr-0`,`psr-4` to ignore either psr-0 or psr-4 for all packages
d.) add an option (2x boolean or 1 string with 3 possible values: `none`,`psr-0`,`psr-4` to ignore either psr-0 or psr-4 for packages with both present (Is there really a usecase when both are needed for the same package in one project? I doubt, but I'm new to package handling...)
e.) add an option (2x array of strings) to ignore psr-0 and psr-4 for a given list of packages

Probably, given he above options, I'd default to d.), as that's automatic, but in certain usecases f.) may be needed.

**Comment by coenjacobs** [comment]
This can now be addressed, by using the override_autoload in the configuration. The (duplicate) PSR-0 autoloader should be removed, using that configuration variable, only defining the PSR-4 one. Testable via the [0.6.0 beta 1](https://github.com/coenjacobs/mozart/releases/tag/0.6.0-beta-1).
