### ISSUE TITLE
Using library nesbot/carbon results in malformed namespace definitions

### ISSUE THREAD

**Issue by coenjacobs** [coenjacobs/mozart#53]
As reported by @danieliser:

>I think it may be related to another issue I mentioned to @coenjacobs on Twitter. Specifically loading the nesbot/carbon library was mucking it all up I think. It seems to be working without that lib. Specifically when we tried to parse that package:

>Namespaces got messed up, instead of `My\Dependencies\Pimple\Container`, we were getting `Pimple\ContainerMy\Dependencies\` which is clearly wrong. It was deleting the files from vendor.

>No idea why, would love to know though.

Related `composer.json` config: https://gist.github.com/danieliser/2a0af213ec608c216bddc7cc7fa76df7

**Comment by coenjacobs** [comment]
@danieliser Can you please verify this still happens with the [0.6.0 beta 3 release](https://github.com/coenjacobs/mozart/releases/tag/0.6.0-beta-3)?

**Comment by BrianHenryIE** [comment]
I can't reproduce this with `0.5.1` or with `dev-master`:

```
{
  "name": "popup-maker/test-plugin",
  "description": "description",
  "minimum-stability": "stable",
  "require": {
    "pimple/pimple": "^3.3",
    "nesbot/carbon": "*"
  },
  "autoload": {
    "psr-4": {
      "DLI\\": "src/"
    }
  },

  "require-dev": {
    "coenjacobs/mozart": "dev-master"
  },
  "extra": {
    "mozart": {
      "dep_namespace": "DLI\\Vendor\\",
      "dep_directory": "/src/Vendor/",
      "classmap_directory": "/includes/classes/",
      "classmap_prefix": "DLI_",
      "packages": [
        "pimple/pimple",
        "nesbot/carbon"
      ]
    },
    "delete_vendor_directories": false
  },
  "scripts": {
    "post-install-cmd": [
      "\"vendor/bin/mozart\" compose",
      "composer dump-autoload"
    ],
    "post-update-cmd": [
      "\"vendor/bin/mozart\" compose",
      "composer dump-autoload"
    ]
  }
}
```

**Comment by danieliser** [comment]
@coenjacobs - Sorry didn't even see the notice for your first comment, glad @BrianHenryIE followed up.

Just tried the with the code @BrianHenryIE, seems to be working correctly for me on `dev-master`.

I have since done a full wipe and reinstall of my OS and switched to working 100% inside of WSL virtual machines for dev stuff, so it is possible the other was somehow a global package conflict.

BUT I did just notice that `"delete_vendor_directories": false` does not seem to prevent package files from being removed from the root `/vendor/` folder. The `/vender/nesbot/carbon/` folder is technically there, but no files inside it.

I'm now wondering if that really means just keep the empty directories or if its supposed to leave package files as well. That could totally be my own confusion.

**Comment by danieliser** [comment]
We can probably mark this one closed @coenjacobs.

**Comment by BrianHenryIE** [comment]
`"delete_vendor_directories": false` wasn't inside the `mozart` key.

```"extra": {
    "mozart": {
      "dep_namespace": "DLI\\Vendor\\",
      "dep_directory": "/src/Vendor/",
      "classmap_directory": "/includes/classes/",
      "classmap_prefix": "DLI_",
      "packages": [
        "pimple/pimple",
        "nesbot/carbon"
      ]
    },
    "delete_vendor_directories": false
  },
```

should be 

```
"extra": {
    "mozart": {
      "dep_namespace": "DLI\\Vendor\\",
      "dep_directory": "/src/Vendor/",
      "classmap_directory": "/includes/classes/",
      "classmap_prefix": "DLI_",
      "packages": [
        "pimple/pimple",
        "nesbot/carbon"
      ]
    "delete_vendor_directories": false
    },
  },
```

**Comment by danieliser** [comment]
🤦‍♂️

**Comment by coenjacobs** [comment]
Glad this got resolved then. 😄
